# Generated by Django 2.0.1 on 2018-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('local', models.CharField(choices=[('L', 'Loja'), ('E', 'Escrtorio')], max_length=1, verbose_name='Local')),
                ('tipo_acesso', models.CharField(choices=[('I', 'Interno'), ('E', 'Externo'), ('IE', 'Externo/Externo')], max_length=1, verbose_name='Tipo Acesso')),
            ],
        ),
    ]
