# Generated by Django 2.0.1 on 2018-10-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='site',
            field=models.CharField(blank=True, max_length=50, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='links',
            name='tipo_acesso',
            field=models.CharField(choices=[('I', 'Interno'), ('E', 'Externo'), ('IE', 'Interno/Externo')], max_length=1, verbose_name='Tipo Acesso'),
        ),
    ]
