# Generated by Django 2.0.1 on 2018-10-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20181028_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='site',
            field=models.CharField(max_length=50, verbose_name='Site'),
        ),
    ]
