# Generated by Django 2.0.1 on 2018-10-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20181028_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='tipo_acesso',
            field=models.CharField(choices=[('I', 'Interno'), ('E', 'Externo'), ('IE', 'Interno/Externo')], max_length=2, verbose_name='Tipo Acesso'),
        ),
    ]
