# Generated by Django 2.0.1 on 2018-10-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_auto_20181028_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='links',
            new_name='Linksites',
        ),
    ]
