# Generated by Django 2.0.1 on 2018-11-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20181103_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptosfiles',
            name='arquivo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
