# Generated by Django 2.0.1 on 2018-12-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_auto_20181103_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=15, verbose_name='Filial')),
                ('bandeira', models.CharField(max_length=10, verbose_name='Bandeira')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='cidade')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=11, verbose_name='CEP')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('tel_fixo', models.CharField(blank=True, max_length=14, verbose_name='Tel. Fixo')),
                ('celular_1', models.CharField(blank=True, max_length=14, verbose_name='Celular 1')),
                ('celular_2', models.CharField(blank=True, max_length=14, verbose_name='Celular 2')),
            ],
            options={
                'verbose_name_plural': 'Filiais',
            },
        ),
        migrations.AlterModelOptions(
            name='deptosfiles',
            options={'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='linksites',
            options={'verbose_name_plural': 'Links'},
        ),
    ]
